# 1. Create a 3x3x3 array with random values 

In [18]:
import numpy as np
arr=np.random.random([3,3,3])
print(arr)

[[[0.07486919 0.13139775 0.845661  ]
  [0.29049669 0.79168725 0.97546328]
  [0.05975515 0.16751851 0.14395214]]

 [[0.63182441 0.29431769 0.44386204]
  [0.81614778 0.57889319 0.69091834]
  [0.39137297 0.36385038 0.21597909]]

 [[0.59758328 0.13340953 0.60050365]
  [0.48873615 0.82033021 0.35656094]
  [0.67393799 0.54682253 0.5926672 ]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [44]:
mat=np.zeros((5,5))
mat=np.diag((1,2,3,4),-1)
mat

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [85]:
check=np.ones((8,8),dtype=int)
print(check)
# Z = np.zeros((8,8),dtype=int)
check[1::2,::2]=0
check[::2,1::2]=0
check

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# 4. Normalize a 5x5 random matrix

In [105]:
norm=np.random.random((5,5))
norm_mean= np.mean(norm)
print(norm)
print('mean is:',norm_mean)
norm_std=np.std(norm)
print('std is :',norm_std)
norm_n=(norm-norm_mean)/norm_std
norm_n

[[0.86693324 0.83181364 0.79999092 0.045918   0.43856099]
 [0.84487128 0.62729353 0.86412203 0.60091757 0.85064742]
 [0.41395194 0.11704923 0.73346338 0.52996704 0.16029233]
 [0.82707046 0.87257696 0.73960293 0.36821572 0.30538057]
 [0.40157209 0.24384326 0.06655867 0.85321855 0.67555366]]
mean is: 0.563175415813488
std is : 0.2791304093191574


array([[ 1.08822907,  0.96241118,  0.84840453, -1.85310306, -0.44643801],
       [ 1.00919087,  0.22970667,  1.07815776,  0.13521335,  1.02988421],
       [-0.53460129, -1.59827151,  0.61006596, -0.11897084, -1.44335076],
       [ 0.94541848,  1.108448  ,  0.63206123, -0.69845381, -0.92356418],
       [-0.57895279, -1.14402497, -1.77915672,  1.03909545,  0.40260122]])

# 5.  How to find common values between two arrays?

In [125]:
set1 = np.random.randint(0,10,10)
set2 = np.random.randint(0,10,10)
set3 = np.intersect1d(set1,set2)
set3

array([3, 5, 6, 7, 8])

# 6.How to get the dates of yesterday, today and tomorrow?

In [138]:
today     = np.datetime64('today')
print(today)
tomorrow = np.datetime64('today')+np.timedelta64(1)
print(tomorrow)
yesterday = np.datetime64('today')-np.timedelta64(1)
print(yesterday)

2020-07-30
2020-07-31
2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [149]:
ran1 = np.random.randint(0,5,5)
print(ran1)
ran2 = np.random.randint(0,5,5)
print(ran2)
print(np.array_equal(ran1,ran2))

[1 1 3 3 4]
[3 0 3 4 3]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [158]:
randm = np.random.random(10)
randm[randm.argmax()]=0
randm

array([0.45591667, 0.38278825, 0.74217377, 0.18096942, 0.70646413,
       0.        , 0.06606131, 0.59107112, 0.65850214, 0.22874816])

# 9. How to print all the values of an array?

In [175]:
arr1=np.arange(6)
for x in arr1:
    print(x)

0
1
2
3
4
5


# 10.Subtract the mean of each row of a matrix

In [198]:
mat1=np.arange(15).reshape(3,5)
mat2=mat1-mat1.mean(axis=1,keepdims=True)
print(mat1)
print(mat2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [272]:
Z = np.arange(10)
Z1 = np.arange(10)
print(Z)
print(len(Z))
I = np.array([8,2, 9, 4, 0, 6, 7, 2, 9, 4, 5, 2, 8, 0, 3, 8, 0, 5, 6, 0])
print(I)
D =np.bincount(I)
print(D)
Z += np.bincount(I, minlength=10)
print(Z)

[0 1 2 3 4 5 6 7 8 9]
10
[8 2 9 4 0 6 7 2 9 4 5 2 8 0 3 8 0 5 6 0]
[4 0 3 1 2 2 2 1 3 2]
[ 4  1  5  4  6  7  8  8 11 11]


# 12.How to get the diagonal of a dot product?

In [273]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))


print("diagonal of a dot product method 1 is....",prod1)

[[0.96081287 0.0425429  0.4996366  0.89286294 0.41290509]
 [0.06733619 0.75025876 0.35447236 0.62545888 0.60776052]
 [0.45686173 0.51148275 0.51652561 0.92543695 0.46582867]
 [0.4506738  0.58127223 0.05855815 0.04417736 0.19228181]
 [0.05391372 0.98410757 0.64709428 0.32347963 0.84405785]]
[[0.06877837 0.87364406 0.95372133 0.74240622 0.14638271]
 [0.90723501 0.88915585 0.00231674 0.44236293 0.9866655 ]
 [0.77240881 0.89101886 0.63239763 0.78860447 0.20800737]
 [0.25835078 0.317003   0.46341628 0.09086132 0.85316454]
 [0.26041515 0.56081351 0.42429376 0.4599225  0.11162536]]
diagonal of a dot product method 1 is.... [0.82880183 1.58087903 1.39006407 0.73034428 1.48367702]


# 13.How to find the most frequent value in an array?

In [282]:
Z = np.random.randint(0,5,10)
print(Z)
print(np.bincount(Z))
print(np.bincount(Z).argmax())

[1 1 3 2 0 1 0 1 3 2]
[2 4 2 2]
1


# 14.How to get the n largest values of an array

In [290]:
arr4=np.arange(10,50)
np.random.shuffle(arr4)
n=6
arr4=arr4[np.argsort(arr4)[-n:]]
arr4

array([44, 45, 46, 47, 48, 49])

# 15.How to create a record array from a regular array?

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)